from pymongo import MongoClient

MONGO_URI = "mongodb+srv://tahoor:12345@vgccluster.vsvyy.mongodb.net/?retryWrites=true&w=majority"

client = MongoClient(MONGO_URI)
db = client["vglamcloset"]  

products_collection = db["Products"]
category_collection = db["Category"]
subcategory_collection = db["SubCategory"]

products = [
    {
        "productID": "P001",
        "productName": "NARS-Powder Blush 237",
        "description": "A silky, blendable powder blush in a soft pink shade, perfect for a natural flush.",
        "price": 9500.00,
        "quantity": 100,
        "imageLink": "\\images\\catalog\\blush\\nars-237.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "ratingCount": 107,
        "ratingTotal": 514,
        "sellingCount": 250,
        "accessCount": 500
    },
    {
        "productID": "P002",
        "productName": "NARS-Powder Blush 252",
        "description": "Highly pigmented powder blush with a rich, warm coral tone for a radiant look.",
        "price": 9500.00,
        "quantity": 150,
        "imageLink": "\\images\\catalog\\blush\\nars-252.png",
        "subCategoryID": "blush",
        "rating": 4.7,
        "ratingCount": 89,
        "ratingTotal": 418,
        "sellingCount": 180,
        "accessCount": 450
    },
    {
        "productID": "P003",
        "productName": "NARS-Powder Blush 775",
        "description": "A smooth and long-lasting blush in a peachy-pink shade for a healthy glow.",
        "price": 9500.00,
        "quantity": 80,
        "imageLink": "\\images\\catalog\\blush\\nars-775.png",
        "subCategoryID": "blush",
        "rating": 4.6,
        "ratingCount": 66,
        "ratingTotal": 304,
        "sellingCount": 200,
        "accessCount": 600
    },
    {
        "productID": "P004",
        "productName": "NARS-Powder Blush 776",
        "description": "A finely milled powder blush in a muted rose tone, delivering a natural finish.",
        "price": 9500.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\blush\\nars-776.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "ratingCount": 112,
        "ratingTotal": 538,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P005",
        "productName": "NARS-Powder Blush 777",
        "description": "A buildable blush in a deep mauve shade, perfect for adding definition to the cheeks.",
        "price": 9500.00,
        "quantity": 60,
        "imageLink": "\\images\\catalog\\blush\\nars-777.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "ratingCount": 59,
        "ratingTotal": 289,
        "sellingCount": 100,
        "accessCount": 200
    },
    {
        "productID": "P006",
        "productName": "NARS-Powder Blush 778",
        "description": "A luminous blush in a warm berry shade, perfect for a soft and elegant look.",
        "price": 9500.00,
        "quantity": 75,
        "imageLink": "\\images\\catalog\\blush\\nars-778.png",
        "subCategoryID": "blush",
        "rating": 4.7,
        "ratingCount": 88,
        "ratingTotal": 414,
        "sellingCount": 140,
        "accessCount": 280
    },
    {
        "productID": "P007",
        "productName": "NARS-Powder Blush 888",
        "description": "A vibrant pink blush with a satin finish for a youthful and radiant look.",
        "price": 9500.00,
        "quantity": 90,
        "imageLink": "\\images\\catalog\\blush\\nars-888.png",
        "subCategoryID": "blush",
        "rating": 4.6,
        "ratingCount": 102,
        "ratingTotal": 469,
        "sellingCount": 170,
        "accessCount": 350
    },
    {
        "productID": "P008",
        "productName": "NARS-Powder Blush 901",
        "description": "A universally flattering rose shade with a soft-matte finish for a fresh complexion.",
        "price": 9500.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\blush\\nars-901.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "ratingCount": 43,
        "ratingTotal": 211,
        "sellingCount": 90,
        "accessCount": 190
    },
    {
        "productID": "P009",
        "productName": "NARS-Powder Blush 902",
        "description": "A highly pigmented blush in a rich plum shade, perfect for contouring and shaping.",
        "price": 9500.00,
        "quantity": 85,
        "imageLink": "\\images\\catalog\\blush\\nars-902.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "ratingCount": 78,
        "ratingTotal": 374,
        "sellingCount": 130,
        "accessCount": 270
    },
    {
        "productID": "P010",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Bliss",
        "description": "A lightweight liquid blush in a soft peach shade, offering a natural and dewy finish.",
        "price": 7000.00,
        "quantity": 120,
        "imageLink": "\\images\\catalog\\blush\\rare-bliss.png",
        "subCategoryID": "blush",
        "rating": 4.5,
        "ratingCount": 92,
        "ratingTotal": 414,
        "sellingCount": 160,
        "accessCount": 320
    },
    {
        "productID": "P011",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Believe",
        "description": "A highly pigmented liquid blush in a cool pink shade that melts into skin for a natural-looking flush.",
        "price": 7000.00,
        "quantity": 80,
        "imageLink": "\\images\\catalog\\blush\\rare-believe.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "ratingCount": 68,
        "ratingTotal": 333,
        "sellingCount": 100,
        "accessCount": 270
    },
    {
        "productID": "P012",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Dewy",
        "description": "A luxurious liquid blush with a dewy finish in a soft coral shade that adds a healthy glow to the skin.",
        "price": 7000.00,
        "quantity": 60,
        "imageLink": "\\images\\catalog\\blush\\rare-dewy.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "ratingCount": 123,
        "ratingTotal": 590,
        "sellingCount": 190,
        "accessCount": 333
    },
    {
        "productID": "P013",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Encourage",
        "description": "A weightless, long-lasting liquid blush in a cheerful bright pink shade that blends effortlessly.",
        "price": 7000.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\blush\\rare-encourage.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "ratingCount": 13,
        "ratingTotal": 62,
        "sellingCount": 45,
        "accessCount": 206
    },
    {
        "productID": "P014",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Grateful",
        "description": "A buildable liquid blush in a warm terracotta shade that creates a sun-kissed, radiant effect.",
        "price": 7000.00,
        "quantity": 130,
        "imageLink": "\\images\\catalog\\blush\\rare-grateful.png",
        "subCategoryID": "blush",
        "rating": 4.5,
        "ratingCount": 56,
        "ratingTotal": 252,
        "sellingCount": 101,
        "accessCount": 290
    },
    {
        "productID": "P015",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Happy",
        "description": "A vibrant coral-orange liquid blush that delivers a playful pop of color with just one drop.",
        "price": 7000.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\blush\\rare-happy.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "ratingCount": 133,
        "ratingTotal": 652,
        "sellingCount": 157,
        "accessCount": 350
    },
    {
        "productID": "P016",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Hope",
        "description": "A silky liquid blush in a soft mauve shade that blends seamlessly for a natural, flushed look.",
        "price": 7000.00,
        "quantity": 90,
        "imageLink": "\\images\\catalog\\blush\\rare-hope.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "ratingCount": 128,
        "ratingTotal": 614,
        "sellingCount": 166,
        "accessCount": 293
    },
    {
        "productID": "P017",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Love",
        "description": "A highly pigmented liquid blush in a true red shade that creates a romantic, rosy flush.",
        "price": 7000.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\blush\\rare-love.png",
        "subCategoryID": "blush",
        "rating": 4.6,
        "ratingCount": 78,
        "ratingTotal": 359,
        "sellingCount": 120,
        "accessCount": 345
    },
    {
        "productID": "P018",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Lucky",
        "description": "A lightweight liquid blush in a bright fuchsia shade that adds a youthful glow to all skin tones.",
        "price": 7000.00,
        "quantity": 110,
        "imageLink": "\\images\\catalog\\blush\\rare-lucky.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "ratingCount": 73,
        "ratingTotal": 358,
        "sellingCount": 129,
        "accessCount": 267
    },
    {
        "productID": "P019",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Virtue",
        "description": "A dreamy liquid blush in a soft lavender-pink shade that adds a delicate flush to the cheeks.",
        "price": 7000.00,
        "quantity": 100,
        "imageLink": "\\images\\catalog\\blush\\rare-virtue.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "ratingCount": 68,
        "ratingTotal": 326,
        "sellingCount": 113,
        "accessCount": 298
    },
    {
        "productID": "P020",
        "productName": "NYX-Can't Stop Won't Stop-Pale",
        "description": "A full-coverage, matte foundation in the lightest shade that controls shine and lasts up to 24 hours.",
        "price": 4200.00,
        "quantity": 76,
        "imageLink": "\\images\\catalog\\foundation\\NYX-pale.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "ratingCount": 108,
        "ratingTotal": 540,
        "sellingCount": 150,
        "accessCount": 200
    },
    {
        "productID": "P021",
        "productName": "NYX-Can't Stop Won't Stop-Light Porcelian",
        "description": "A lightweight, waterproof foundation in a very fair shade with cool undertones for flawless, transfer-proof coverage.",
        "price": 4200.00,
        "quantity": 43,
        "imageLink": "\\images\\catalog\\foundation\\NYX-light-porcelian.png",
        "subCategoryID": "foundation",
        "rating": 4.9,
        "ratingCount": 35,
        "ratingTotal": 172,
        "sellingCount": 88,
        "accessCount": 135
    },
    {
        "productID": "P022",
        "productName": "NYX-Can't Stop Won't Stop-Light Ivory",
        "description": "A creamy, non-comedogenic foundation in a fair shade with neutral undertones that controls oil and minimizes pores.",
        "price": 4200.00,
        "quantity": 56,
        "imageLink": "\\images\\catalog\\foundation\\NYX-light-ivory.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "ratingCount": 27,
        "ratingTotal": 135,
        "sellingCount": 65,
        "accessCount": 89
    },
    {
        "productID": "P023",
        "productName": "NYX-Can't Stop Won't Stop-Light",
        "description": "A high-pigment, long-wearing foundation in a light shade that provides seamless coverage with a natural matte finish.",
        "price": 4200.00,
        "quantity": 23,
        "imageLink": "\\images\\catalog\\foundation\\NYX-light.png",
        "subCategoryID": "foundation",
        "rating": 4.7,
        "ratingCount": 99,
        "ratingTotal": 465,
        "sellingCount": 134,
        "accessCount": 211
    },
    {
        "productID": "P024",
        "productName": "NYX-Can't Stop Won't Stop-Fair",
        "description": "A buildable, transfer-resistant foundation in a fair shade with slight warm undertones for a smooth, even complexion.",
        "price": 4200.00,
        "quantity": 77,
        "imageLink": "\\images\\catalog\\foundation\\NYX-fair.png",
        "subCategoryID": "foundation",
        "rating": 4.8,
        "ratingCount": 112,
        "ratingTotal": 538,
        "sellingCount": 156,
        "accessCount": 299
    },
    {
        "productID": "P025",
        "productName": "NYX-Can't Stop Won't Stop-Vanilla",
        "description": "A vegan, cruelty-free foundation in a light-medium shade with neutral undertones for a flawless, matte finish.",
        "price": 4200.00,
        "quantity": 29,
        "imageLink": "\\images\\catalog\\foundation\\NYX-vanilla.png",
        "subCategoryID": "foundation",
        "rating": 4.4,
        "ratingCount": 109,
        "ratingTotal": 480,
        "sellingCount": 155,
        "accessCount": 254
    },
    {
        "productID": "P026",
        "productName": "NYX-Can't Stop Won't Stop-Warm Vanilla",
        "description": "A full-coverage foundation in a light-medium shade with golden undertones that stays fresh throughout the day.",
        "price": 4200.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\foundation\\NYX-warm-vanilla.png",
        "subCategoryID": "foundation",
        "rating": 4.0,
        "ratingCount": 93,
        "ratingTotal": 372,
        "sellingCount": 123,
        "accessCount": 298
    },
    {
        "productID": "P027",
        "productName": "NYX-Can't Stop Won't Stop-Nude",
        "description": "A lightweight, breathable foundation in a medium nude shade with neutral undertones for a natural skin-like finish.",
        "price": 4200.00,
        "quantity": 97,
        "imageLink": "\\images\\catalog\\foundation\\NYX-nude.png",
        "subCategoryID": "foundation",
        "rating": 4.3,
        "ratingCount": 8,
        "ratingTotal": 34,
        "sellingCount": 17,
        "accessCount": 113
    },
    {
        "productID": "P028",
        "productName": "NYX-Can't Stop Won't Stop-Natural",
        "description": "Long-wearing foundation with a matte finish in Natural shade, perfect for everyday wear. Provides full coverage that lasts up to 24 hours.",
        "price": 4200.00,
        "quantity": 89,
        "imageLink": "\\images\\catalog\\foundation\\NYX-natural.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "ratingCount": 77,
        "ratingTotal": 385,
        "sellingCount": 103,
        "accessCount": 209
    },
    {
        "productID": "P029",
        "productName": "NYX-Can't Stop Won't Stop-True Beige",
        "description": "Lightweight, waterproof foundation in True Beige shade with a natural matte finish. Provides full coverage and controls shine throughout the day.",
        "price": 4200.00,
        "quantity": 67,
        "imageLink": "\\images\\catalog\\foundation\\NYX-true-beige.png",
        "subCategoryID": "foundation",
        "rating": 4.5,
        "ratingCount": 41,
        "ratingTotal": 185,
        "sellingCount": 93,
        "accessCount": 181
    },
    {
        "productID": "P030",
        "productName": "NYX-Can't Stop Won't Stop-Buff",
        "description": "High-pigment, transfer-proof foundation in Buff shade. Oil-free formula suitable for normal to oily skin types with a seamless finish.",
        "price": 4200.00,
        "quantity": 92,
        "imageLink": "\\images\\catalog\\foundation\\NYX-buff.png",
        "subCategoryID": "foundation",
        "rating": 4.9,
        "ratingCount": 9,
        "ratingTotal": 44,
        "sellingCount": 17,
        "accessCount": 118
    },
    {
        "productID": "P031",
        "productName": "NYX-Can't Stop Won't Stop-Medium Buff",
        "description": "Buildable coverage foundation in Medium Buff shade with a comfortable, non-cakey formula. Resists sweat and humidity for all-day wear.",
        "price": 4200.00,
        "quantity": 71,
        "imageLink": "\\images\\catalog\\foundation\\NYX-medium-buff.png",
        "subCategoryID": "foundation",
        "rating": 4.9,
        "ratingCount": 59,
        "ratingTotal": 289,
        "sellingCount": 109,
        "accessCount": 231
    },
    {
        "productID": "P032",
        "productName": "NYX-Can't Stop Won't Stop-Medium Olive",
        "description": "Non-comedogenic foundation in Medium Olive shade with a velvety matte finish. Offers full coverage that lasts all day without fading.",
        "price": 4200.00,
        "quantity": 28,
        "imageLink": "\\images\\catalog\\foundation\\NYX-medium-olive.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "ratingCount": 119,
        "ratingTotal": 595,
        "sellingCount": 161,
        "accessCount": 267
    },
    {
        "productID": "P033",
        "productName": "NYX-Can't Stop Won't Stop-Soft Beige",
        "description": "Creamy, blendable foundation in Soft Beige shade that provides medium to full coverage. Perfect for combination skin with a long-lasting finish.",
        "price": 4200.00,
        "quantity": 83,
        "imageLink": "\\images\\catalog\\foundation\\NYX-soft-beige.png",
        "subCategoryID": "foundation",
        "rating": 4.8,
        "ratingCount": 83,
        "ratingTotal": 398,
        "sellingCount": 102,
        "accessCount": 234
    },
    {
        "productID": "P034",
        "productName": "NARS-Afterglow Irresistible Eyeshadow Palette",
        "description": "Limited edition palette featuring 12 highly-pigmented, blendable eyeshadows in warm neutral tones with matte, shimmer, and metallic finishes.",
        "price": 9590.00,
        "quantity": 83,
        "imageLink": "\\images\\catalog\\eyeshadow\\afterglow.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "ratingCount": 19,
        "ratingTotal": 93,
        "sellingCount": 37,
        "accessCount": 192
    },
    {
        "productID": "P035",
        "productName": "Dasique-Berry Smoothie Eyeshadow Palette",
        "description": "Compact 9-shade palette featuring versatile berry and mauve tones. Includes both matte and shimmer finishes with minimal fallout and high color payoff.",
        "price": 8000.00,
        "quantity": 57,
        "imageLink": "\\images\\catalog\\eyeshadow\\berry-smoothie.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.8,
        "ratingCount": 24,
        "ratingTotal": 115,
        "sellingCount": 42,
        "accessCount": 178
    },
    {
        "productID": "P036",
        "productName": "Dasique-Candy Berry Eyeshadow Palette",
        "description": "Curated collection of 9 vibrant berry-toned shadows perfect for creating playful and romantic eye looks. Features buttery-soft formula with excellent blendability.",
        "price": 6950.00,
        "quantity": 68,
        "imageLink": "\\images\\catalog\\eyeshadow\\candy-berry.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "ratingCount": 18,
        "ratingTotal": 86,
        "sellingCount": 39,
        "accessCount": 165
    },
    {
        "productID": "P037",
        "productName": "NYX-Ultimate Glow Shots Liquid Eyeshadow",
        "description": "High-impact liquid eyeshadow with intense shimmer and glitter finish. Quick-drying formula that doesn't crease and stays vibrant all day.",
        "price": 3000.00,
        "quantity": 95,
        "imageLink": "\\images\\catalog\\eyeshadow\\glowshots.png",
        "subCategoryID": "eyeshadow",
        "rating": 5.0,
        "ratingCount": 37,
        "ratingTotal": 185,
        "sellingCount": 51,
        "accessCount": 220
    },
    {
        "productID": "P038",
        "productName": "NARS-Hardwired Eyeshadows",
        "description": "Single pot eyeshadows with an intense metallic finish and multi-dimensional shimmer. Highly-pigmented formula that applies smoothly with minimal fallout.",
        "price": 4300.00,
        "quantity": 72,
        "imageLink": "\\images\\catalog\\eyeshadow\\hardwired.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "ratingCount": 20,
        "ratingTotal": 98,
        "sellingCount": 34,
        "accessCount": 140
    },
    {
        "productID": "P039",
        "productName": "Huda Beauty-Icy Nude Eyeshadow Palette",
        "description": "Luxury 18-shade palette featuring cool-toned nudes with innovative textures including matte, shimmer, glitter, and multi-chrome finishes for endless eye looks.",
        "price": 12500.00,
        "quantity": 43,
        "imageLink": "\\images\\catalog\\eyeshadow\\icy-nude.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.6,
        "ratingCount": 14,
        "ratingTotal": 64,
        "sellingCount": 29,
        "accessCount": 110
    },
    {
        "productID": "P040",
        "productName": "NARS-Single Eyeshadows",
        "description": "Professional-quality single eyeshadows with rich color payoff in a range of finishes. Silky texture allows for effortless application and blending.",
        "price": 3700.00,
        "quantity": 81,
        "imageLink": "\\images\\catalog\\eyeshadow\\single.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "ratingCount": 23,
        "ratingTotal": 113,
        "sellingCount": 47,
        "accessCount": 155
    },
    {
        "productID": "P041",
        "productName": "NYX-Ultimate Utopia 40 Pan Palette",
        "description": "Expansive palette featuring 40 unique shades ranging from neutrals to bold pops of color. Includes matte, satin, shimmer, and metallic finishes for unlimited creative looks.",
        "price": 9800.00,
        "quantity": 64,
        "imageLink": "\\images\\catalog\\eyeshadow\\ultimate-utopia.png",
        "subCategoryID": "eyeshadow",
        "rating": 5.0,
        "ratingCount": 31,
        "ratingTotal": 155,
        "sellingCount": 45,
        "accessCount": 170
    },
    {
        "productID": "P042",
        "productName": "NYX-Ultimate Vintage Jean Palette",
        "description": "Trendy palette inspired by denim hues with 16 wearable blue, gray, and neutral shades in various finishes. Perfect for creating everyday to dramatic eye looks.",
        "price": 5600.00,
        "quantity": 78,
        "imageLink": "\\images\\catalog\\eyeshadow\\vintage-jean.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "ratingCount": 19,
        "ratingTotal": 93,
        "sellingCount": 38,
        "accessCount": 135
    },
    {
        "productID": "P043",
        "productName": "Dasique-Violet Knit Eyeshadow Palette",
        "description": "Versatile 9-shade palette featuring purple-toned neutrals in both matte and shimmer finishes. Finely-milled formula offers seamless blending and buildable pigmentation.",
        "price": 6950.00,
        "quantity": 59,
        "imageLink": "\\images\\catalog\\eyeshadow\\violet-knit.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.8,
        "ratingCount": 15,
        "ratingTotal": 72,
        "sellingCount": 33,
        "accessCount": 125
    },
    {
        "productID": "P044",
        "productName": "NYX High Shine-Ambition Statement",
        "description": "Vibrant red lipstick with a high-shine finish that provides intense color payoff and hydration. Non-sticky formula with comfortable wear throughout the day.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-ambition-statement.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "ratingCount": 57,
        "ratingTotal": 279,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P045",
        "productName": "NYX High Shine-Born to Hustle",
        "description": "Rich berry-toned lipstick with a glossy finish that delivers brilliant shine and medium coverage. Infused with shea butter for moisturizing comfort.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-born-to-hustle.png",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "ratingCount": 88,
        "ratingTotal": 422,
        "sellingCount": 137,
        "accessCount": 313
    },
    {
        "productID": "P046",
        "productName": "NYX High Shine-Movie Maker",
        "description": "Bold pink lipstick with high-shine formula that creates a plumping effect. Lightweight texture with a smooth application and lasting color.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-ambition-statement.png",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "ratingCount": 78,
        "ratingTotal": 374,
        "sellingCount": 108,
        "accessCount": 296
    },
    {
        "productID": "P047",
        "productName": "NYX High Shine-Boundary Pusher",
        "description": "Statement-making deep plum lipstick with a brilliant glossy finish. Enriched with vitamin E to nourish lips while providing intense color payoff.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-boundary-pusher.png",
        "subCategoryID": "lipstick",
        "rating": 4.7,
        "ratingCount": 107,
        "ratingTotal": 503,
        "sellingCount": 128,
        "accessCount": 345
    },
    {
        "productID": "P048",
        "productName": "NYX High Shine-Goal Crusher",
        "description": "Flattering coral lipstick with high-shine finish and medium coverage. Creamy formula glides on smoothly and provides a hint of plumping effect.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-goal-crusher.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "ratingCount": 85,
        "ratingTotal": 417,
        "sellingCount": 126,
        "accessCount": 341
    },
    {
        "productID": "P049",
        "productName": "NYX High Shine-Goal Getter",
        "description": "Sophisticated nude-pink lipstick with glass-like shine. Features a non-sticky formula that feels comfortable on lips with a subtle sweet scent.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-goal-getter.png",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "ratingCount": 89,
        "ratingTotal": 427,
        "sellingCount": 118,
        "accessCount": 278
    },
    {
        "productID": "P050",
        "productName": "NYX High Shine-Movin' Up",
        "description": "Versatile mauve lipstick with a high-shine finish for everyday wear. Buildable formula allows for sheer to medium coverage with a cushiony feel.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-movin-up.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "ratingCount": 83,
        "ratingTotal": 407,
        "sellingCount": 116,
        "accessCount": 318
    },
    {
        "productID": "P051",
        "productName": "Maybelline Superstay Vinyl Ink-Charmed",
        "description": "Long-wearing liquid lipstick in a charming rosy shade with a high-shine vinyl finish. Transfer-resistant formula that lasts up to 16 hours.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-charmed.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "ratingCount": 102,
        "ratingTotal": 500,
        "sellingCount": 146,
        "accessCount": 378
    },
    {
        "productID": "P052",
        "productName": "Maybelline Superstay Vinyl Ink-Cheeky",
        "description": "Vibrant coral liquid lipstick with a glossy vinyl finish. Innovative formula combines the staying power of a stain with the shine of a gloss.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-cheeky.jpg",
        "subCategoryID": "lipstick",
        "rating": 5.0,
        "ratingCount": 74,
        "ratingTotal": 370,
        "sellingCount": 109,
        "accessCount": 299
    },
    {
        "productID": "P053",
        "productName": "Maybelline Superstay Vinyl Ink-Coy",
        "description": "Soft pink liquid lipstick with a glossy vinyl finish. Features a long-lasting formula that stays put for up to 16 hours without drying out lips.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-coy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "ratingCount": 68,
        "ratingTotal": 326,
        "sellingCount": 100,
        "accessCount": 250
    },
    {
        "productID": "P054",
        "productName": "Maybelline Superstay Vinyl Ink-Lippy",
        "description": "Vibrant fuchsia liquid lipstick with a high-shine vinyl finish. Two-phase formula that delivers intense color that resists transfer and fading.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-lippy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "ratingCount": 97,
        "ratingTotal": 475,
        "sellingCount": 130,
        "accessCount": 280
    },
    {
        "productID": "P055",
        "productName": "Maybelline Superstay Vinyl Ink-Peachy",
        "description": "Fresh peach-toned liquid lipstick with a glossy finish. Lightweight formula that doesn't smudge or bleed, perfect for everyday wear.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-peachy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "ratingCount": 109,
        "ratingTotal": 534,
        "sellingCount": 140,
        "accessCount": 290
    },
    {
        "productID": "P056",
        "productName": "Maybelline Superstay Vinyl Ink-Peppy",
        "description": "Bright coral liquid lipstick with a mirror-like shine. Innovative formula that combines staying power with comfortable wear and no sticky feeling.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-peppy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "ratingCount": 49,
        "ratingTotal": 235,
        "sellingCount": 110,
        "accessCount": 270
    },
    {
        "productID": "P057",
        "productName": "Maybelline Superstay Vinyl Ink-Pink Mashup",
        "description": "Unique dusty rose liquid lipstick with a vinyl finish. Features a dual-phase formula that separates for optimal color payoff and shine.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-pink-mashup.jpg",
        "subCategoryID": "lipstick",
        "rating": 5.0,
        "ratingCount": 104,
        "ratingTotal": 520,
        "sellingCount": 150,
        "accessCount": 310
    },
    {
        "productID": "P058",
        "productName": "Maybelline Superstay Vinyl Ink-Red Hot",
        "description": "Classic true red liquid lipstick with a high-shine finish. Long-wearing formula that maintains vibrant color and glossy look throughout the day.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-red-hot.jpg",
        "subCategoryID": "lipstick",
        "rating": 5.0,
        "ratingCount": 117,
        "ratingTotal": 585,
        "sellingCount": 160,
        "accessCount": 320
    },
    {
        "productID": "P059",
        "productName": "Maybelline Superstay Vinyl Ink-Rogue",
        "description": "Deep crimson liquid lipstick with a dimensional vinyl finish. Waterproof formula that withstands eating and drinking without transferring.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-rogue.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "ratingCount": 106,
        "ratingTotal": 519,
        "sellingCount": 135,
        "accessCount": 295
    },
    {
        "productID": "P060",
        "productName": "Maybelline Superstay Vinyl Ink-Unrivaled",
        "description": "Bold burgundy liquid lipstick with a high-shine vinyl finish. Formula that doesn't feather or smudge, offering long-lasting wear for special occasions.",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-unrivaled.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "ratingCount": 94,
        "ratingTotal": 451,
        "sellingCount": 138,
        "accessCount": 319
    },
    {
        "productID": "P061",
        "productName": "Midnight Shades",
        "description": "Elegant black sunglasses with a sleek finish.",
        "price": 3000.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-1.png",
        "subCategoryID": "sunglasses",
        "rating": 4.9,
        "ratingCount": 36,
        "ratingTotal": 176,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P062",
        "productName": "Noir Frames",
        "description": "Minimalist sunglasses with premium lens protection.",
        "price": 3500.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-2.png",
        "subCategoryID": "sunglasses",
        "rating": 4.9,
        "ratingCount": 29,
        "ratingTotal": 142,
        "sellingCount": 110,
        "accessCount": 280
    },
    {
        "productID": "P063",
        "productName": "Eclipse Wear",
        "description": "Stylish dark-lensed sunglasses with UV protection.",
        "price": 3800.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-3.png",
        "subCategoryID": "sunglasses",
        "rating": 4.8,
        "ratingCount": 41,
        "ratingTotal": 197,
        "sellingCount": 105,
        "accessCount": 260
    },
    {
        "productID": "P064",
        "productName": "Shadow Specs",
        "description": "Trendy oversized sunglasses for a bold look.",
        "price": 4500.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-4.png",
        "subCategoryID": "sunglasses",
        "rating": 4.7,
        "ratingCount": 37,
        "ratingTotal": 174,
        "sellingCount": 100,
        "accessCount": 250
    },
    {
        "productID": "P065",
        "productName": "Amber Vision",
        "description": "Amber-tinted sunglasses for a sophisticated style.",
        "price": 3200.00,
        "quantity": 45,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-5.png",
        "subCategoryID": "sunglasses",
        "rating": 4.8,
        "ratingCount": 28,
        "ratingTotal": 134,
        "sellingCount": 98,
        "accessCount": 240
    },
    {
        "productID": "P066",
        "productName": "Vintage Waves",
        "description": "Retro-style sunglasses with a classic design.",
        "price": 2800.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-6.png",
        "subCategoryID": "sunglasses",
        "rating": 4.7,
        "ratingCount": 25,
        "ratingTotal": 118,
        "sellingCount": 90,
        "accessCount": 230
    },
    {
        "productID": "P067",
        "productName": "Sunset Glaze",
        "description": "Gradient-lens sunglasses for a chic summer look.",
        "price": 3900.00,
        "quantity": 35,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-7.png",
        "subCategoryID": "sunglasses",
        "rating": 4.9,
        "ratingCount": 56,
        "ratingTotal": 274,
        "sellingCount": 110,
        "accessCount": 270
    },
    {
        "productID": "P068",
        "productName": "Crystal View",
        "description": "Transparent-frame sunglasses for a modern touch.",
        "price": 3100.00,
        "quantity": 42,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-8.png",
        "subCategoryID": "sunglasses",
        "rating": 4.6,
        "ratingCount": 39,
        "ratingTotal": 179,
        "sellingCount": 95,
        "accessCount": 220
    },
    {
        "productID": "P069",
        "productName": "Ocean Blue",
        "description": "Blue-lens sunglasses with a sleek metallic frame.",
        "price": 3400.00,
        "quantity": 38,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-9.png",
        "subCategoryID": "sunglasses",
        "rating": 4.8,
        "ratingCount": 38,
        "ratingTotal": 182,
        "sellingCount": 100,
        "accessCount": 250
    },
    {
        "productID": "P070",
        "productName": "Golden Luxe",
        "description": "Gold-plated frame sunglasses for a luxury appeal.",
        "price": 5000.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-10.png",
        "subCategoryID": "sunglasses",
        "rating": 5.0,
        "ratingCount": 74,
        "ratingTotal": 370,
        "sellingCount": 130,
        "accessCount": 310
    },
    {
        "productID": "P071", 
        "productName": "Pink Earrings",
        "description": "Delicate pink gemstone earrings with sterling silver posts. Elegant tear-drop shape adds a feminine touch to any outfit.",
        "price": 3000.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\jewelry\\j1.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "ratingCount": 39,
        "ratingTotal": 191,
        "sellingCount": 90,
        "accessCount": 200
    },
    {
        "productID": "P072", 
        "productName": "Gold Flower Earrings",
        "description": "Intricate gold-plated flower-shaped stud earrings. Delicate petal design with hypoallergenic posts suitable for sensitive ears.",
        "price": 2000.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\jewelry\\j2.png",
        "subCategoryID": "jewelry",
        "rating": 4.7,
        "ratingCount": 18,
        "ratingTotal": 86,
        "sellingCount": 80,
        "accessCount": 180
    },
    {
        "productID": "P073", 
        "productName": "Drop Earrings",
        "description": "Elegant silver-tone drop earrings with crystal accents. Lightweight design with secure butterfly backs for comfortable all-day wear.",
        "price": 2500.00,
        "quantity": 35,
        "imageLink": "\\images\\catalog\\jewelry\\j3.png",
        "subCategoryID": "jewelry",
        "rating": 4.8,
        "ratingCount": 29,
        "ratingTotal": 139,
        "sellingCount": 95,
        "accessCount": 210
    },
    {
        "productID": "P074", 
        "productName": "Retro Pearl Earrings",
        "description": "Vintage-inspired earrings featuring genuine freshwater pearls in an antique gold setting. Timeless design perfect for special occasions.",
        "price": 3500.00,
        "quantity": 25,
        "imageLink": "\\images\\catalog\\jewelry\\j4.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "ratingCount": 30,
        "ratingTotal": 147,
        "sellingCount": 85,
        "accessCount": 190
    },
    {
        "productID": "P075", 
        "productName": "Red Drop Earrings",
        "description": "Statement ruby-red crystal drop earrings with rhodium plating. Eye-catching design that catches the light for a dramatic effect.",
        "price": 4500.00,
        "quantity": 20,
        "imageLink": "\\images\\catalog\\jewelry\\j5.png",
        "subCategoryID": "jewelry",
        "rating": 5.0,
        "ratingCount": 43,
        "ratingTotal": 215,
        "sellingCount": 100,
        "accessCount": 220
    },
    {
        "productID": "P076", 
        "productName": "Casual Studs",
        "description": "Everyday minimalist stud earrings in brushed gold finish. Versatile geometric design that pairs well with any outfit.",
        "price": 2500.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\jewelry\\j6.png",
        "subCategoryID": "jewelry",
        "rating": 4.8,
        "ratingCount": 28,
        "ratingTotal": 134,
        "sellingCount": 90,
        "accessCount": 200
    },
    {
        "productID": "P077", 
        "productName": "Blue Drop Earrings",
        "description": "Luxurious sapphire-blue crystal earrings with an elegant drop design. Features secure lever backs and rhodium-plated settings.",
        "price": 4500.00,
        "quantity": 20,
        "imageLink": "\\images\\catalog\\jewelry\\j7.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "ratingCount": 62,
        "ratingTotal": 304,
        "sellingCount": 105,
        "accessCount": 230
    },
    {
        "productID": "P078", 
        "productName": "Bow Pearl Earrings",
        "description": "Charming bow-shaped earrings featuring delicate pearls. Feminine design with 14K gold-plated details for a touch of luxury.",
        "price": 1500.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\jewelry\\j8.png",
        "subCategoryID": "jewelry",
        "rating": 4.8,
        "ratingCount": 21,
        "ratingTotal": 101,
        "sellingCount": 75,
        "accessCount": 170
    },
    {
        "productID": "P079", 
        "productName": "Golden Hoops",
        "description": "Classic gold-tone hoop earrings in a versatile medium size. Lightweight design with a secure click closure for comfortable wear.",
        "price": 750.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\jewelry\\j9.png",
        "subCategoryID": "jewelry",
        "rating": 4.7,
        "ratingCount": 78,
        "ratingTotal": 367,
        "sellingCount": 110,
        "accessCount": 240
    },
    {
        "productID": "P080", 
        "productName": "Sparkle Studs",
        "description": "Brilliant cubic zirconia stud earrings with exceptional clarity. Prong-set stones in a platinum-plated setting for maximum sparkle.",
        "price": 3500.00,
        "quantity": 25,
        "imageLink": "\\images\\catalog\\jewelry\\j10.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "ratingCount": 35,
        "ratingTotal": 172,
        "sellingCount": 95,
        "accessCount": 215
    },
    {
        "productID": "P081", 
        "productName": "Crystal Earrings",
        "description": "Sophisticated drop earrings featuring multi-faceted crystal stones. Artfully designed with a mix of clear and colored crystals for maximum sparkle and elegance",
        "price": 4500.00,
        "quantity": 20,
        "imageLink": "\\images\\catalog\\jewelry\\j11.png",
        "subCategoryID": "jewelry",
        "rating": 5.0,
        "ratingCount": 86,
        "ratingTotal": 430,
        "sellingCount": 137,
        "accessCount": 250
    }
]
category_collection = [
    {
        "categoryID": "C001",
        "categoryName": "Makeup"
    },
    {
        "categoryID": "C002",
        "categoryName": "Accessory"
    }
]
subcategory_collection = [
    {
        "subCategoryID": "blush",
        "subCategoryName": "blush",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "foundation",
        "subCategoryName": "foundation",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "eyeshadow",
        "subCategoryName": "eyeshadow",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "lipstick",
        "subCategoryName": "lipstick",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "jewelry",
        "subCategoryName": "jewelry",
        "categoryID": "C002"
    },
    {
        "subCategoryID": "sunglasses",
        "subCategoryName": "sunglasses",
        "categoryID": "C002"
    }
]

if __name__ == "__main__":
    try:
        products_collection.insert_many(products)
        print("Products inserted successfully into the Products collection!")
    except Exception as e:
        print(f"Error inserting products: {e}")

