from pymongo import MongoClient

MONGO_URI = "mongodb+srv://tahoor:12345@vgccluster.vsvyy.mongodb.net/?retryWrites=true&w=majority"

client = MongoClient(MONGO_URI)
db = client["vglamcloset"]  

products_collection = db["Products"]
category_collection = db["Category"]
subcategory_collection = db["SubCategory"]

products = [
        {
        "productID": "P001",
        "productName": "NARS-Powder Blush 237",
        "description": "",
        "price": 9500.00,
        "quantity": 100,
        "imageLink": "\\images\\catalog\\blush\\nars-237.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "sellingCount": 250,
        "accessCount": 500
    },
    {
        "productID": "P002",
        "productName": "NARS-Powder Blush 252",
        "description": "",
        "price": 9500.00,
        "quantity": 150,
        "imageLink": "\\images\\catalog\\blush\\nars-252.png",
        "subCategoryID": "blush",
        "rating": 4.7,
        "sellingCount": 180,
        "accessCount": 450
    },
    {
        "productID": "P003",
        "productName": "NARS-Powder Blush 775",
        "description": "",
        "price": 9500.00,
        "quantity": 80,
        "imageLink": "\\images\\catalog\\blush\\nars-775.png",
        "subCategoryID": "blush",
        "rating": 4.6,
        "sellingCount": 200,
        "accessCount": 600
    },
    {
        "productID": "P004",
        "productName": "NARS-Powder Blush 776",
        "description": "",
        "price": 9500.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\blush\\nars-776.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P005",
        "productName": "NARS-Powder Blush 777",
        "description": "",
        "price": 9500.00,
        "quantity": 60,
        "imageLink": "\\images\\catalog\\blush\\nars-777.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "sellingCount": 100,
        "accessCount": 200
    },
    {
        "productID": "P006",
        "productName": "NARS-Powder Blush 778",
        "description": "",
        "price": 9500.00,
        "quantity": 75,
        "imageLink": "\\images\\catalog\\blush\\nars-778.png",
        "subCategoryID": "blush",
        "rating": 4.7,
        "sellingCount": 140,
        "accessCount": 280
    },
    {
        "productID": "P007",
        "productName": "NARS-Powder Blush 888",
        "description": "",
        "price": 9500.00,
        "quantity": 90,
        "imageLink": "\\images\\catalog\\blush\\nars-888.png",
        "subCategoryID": "blush",
        "rating": 4.6,
        "sellingCount": 170,
        "accessCount": 350
    },
    {
        "productID": "P008",
        "productName": "NARS-Powder Blush 901",
        "description": "",
        "price": 9500.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\blush\\nars-901.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "sellingCount": 90,
        "accessCount": 190
    },
    {
        "productID": "P009",
        "productName": "NARS-Powder Blush 902",
        "description": "",
        "price": 9500.00,
        "quantity": 85,
        "imageLink": "\\images\\catalog\\blush\\nars-902.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "sellingCount": 130,
        "accessCount": 270
    },
    {
        "productID": "P010",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Bliss",
        "description": "",
        "price": 7000.00,
        "quantity": 120,
        "imageLink": "\\images\\catalog\\blush\\rare-bliss.png",
        "subCategoryID": "blush",
        "rating": 4.5,
        "sellingCount": 160,
        "accessCount": 320
    },
    {
        "productID": "P011",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Believe",
        "description": "",
        "price": 7000.00,
        "quantity": 80,
        "imageLink": "\\images\\catalog\\blush\\rare-believe.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "sellingCount": 100,
        "accessCount": 270
    },
    {
        "productID": "P012",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Dewy",
        "description": "",
        "price": 7000.00,
        "quantity": 60,
        "imageLink": "\\images\\catalog\\blush\\rare-dewy.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "sellingCount": 190,
        "accessCount": 333
    },
    {
        "productID": "P013",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Encourage",
        "description": "",
        "price": 7000.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\blush\\rare-encourage.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "sellingCount": 45,
        "accessCount": 206
    },
    {
        "productID": "P014",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Grateful",
        "description": "",
        "price": 7000.00,
        "quantity": 130,
        "imageLink": "\\images\\catalog\\blush\\rare-grateful.png",
        "subCategoryID": "blush",
        "rating": 4.5,
        "sellingCount": 101,
        "accessCount": 290
    },
    {
        "productID": "P015",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Happy",
        "description": "",
        "price": 7000.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\blush\\rare-happy.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "sellingCount": 57,
        "accessCount": 350
    },
    {
        "productID": "P016",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Hope",
        "description": "",
        "price": 7000.00,
        "quantity": 90,
        "imageLink": "\\images\\catalog\\blush\\rare-hope.png",
        "subCategoryID": "blush",
        "rating": 4.7,
        "sellingCount": 66,
        "accessCount": 293
    },
    {
        "productID": "P017",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Love",
        "description": "",
        "price": 7000.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\blush\\rare-love.png",
        "subCategoryID": "blush",
        "rating": 4.6,
        "sellingCount": 120,
        "accessCount": 345
    },
    {
        "productID": "P018",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Lucky",
        "description": "",
        "price": 7000.00,
        "quantity": 110,
        "imageLink": "\\images\\catalog\\blush\\rare-lucky.png",
        "subCategoryID": "blush",
        "rating": 4.9,
        "sellingCount": 129,
        "accessCount": 267
    },
    {
        "productID": "P019",
        "productName": "Rare Beauty-Soft Pinch Liquid Blush-Virtue",
        "description": "",
        "price": 7000.00,
        "quantity": 100,
        "imageLink": "\\images\\catalog\\blush\\rare-virtue.png",
        "subCategoryID": "blush",
        "rating": 4.8,
        "sellingCount": 113,
        "accessCount": 298
    },
    {
        "productID": "P020",
        "productName": "NYX-Can't Stop Won't Stop-Pale",
        "description": "",
        "price": 4200.00,
        "quantity": 76,
        "imageLink": "\\images\\catalog\\foundation\\NYX-pale.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "sellingCount": 150,
        "accessCount": 200
    },
    {
        "productID": "P021",
        "productName": "NYX-Can't Stop Won't Stop-Light Porcelian",
        "description": "",
        "price": 4200.00,
        "quantity": 43,
        "imageLink": "\\images\\catalog\\foundation\\NYX-light-porcelian.png",
        "subCategoryID": "foundation",
        "rating": 4.9,
        "sellingCount": 88,
        "accessCount": 135
    },
    {
        "productID": "P022",
        "productName": "NYX-Can't Stop Won't Stop-Light Ivory",
        "description": "",
        "price": 4200.00,
        "quantity": 56,
        "imageLink": "\\images\\catalog\\foundation\\NYX-light-ivory.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "sellingCount": 65,
        "accessCount": 89
    },
    {
        "productID": "P023",
        "productName": "NYX-Can't Stop Won't Stop-Light",
        "description": "",
        "price": 4200.00,
        "quantity": 23,
        "imageLink": "\\images\\catalog\\foundation\\NYX-light.png",
        "subCategoryID": "foundation",
        "rating": 4.7,
        "sellingCount": 134,
        "accessCount": 211
    },
    {
        "productID": "P024",
        "productName": "NYX-Can't Stop Won't Stop-Fair",
        "description": "",
        "price": 4200.00,
        "quantity": 77,
        "imageLink": "\\images\\catalog\\foundation\\NYX-fair.png",
        "subCategoryID": "foundation",
        "rating": 4.8,
        "sellingCount": 156,
        "accessCount": 299
    },
    {
        "productID": "P025",
        "productName": "NYX-Can't Stop Won't Stop-Vanilla",
        "description": "",
        "price": 4200.00,
        "quantity": 29,
        "imageLink": "\\images\\catalog\\foundation\\NYX-vanilla.png",
        "subCategoryID": "foundation",
        "rating": 4.4,
        "sellingCount": 155,
        "accessCount": 254
    },
    {
        "productID": "P026",
        "productName": "NYX-Can't Stop Won't Stop-Warm Vanilla",
        "description": "",
        "price": 4200.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\foundation\\NYX-warm-vanilla.png",
        "subCategoryID": "foundation",
        "rating": 4.0,
        "sellingCount": 123,
        "accessCount": 298
    },
    {
        "productID": "P027",
        "productName": "NYX-Can't Stop Won't Stop-Nude",
        "description": "",
        "price": 4200.00,
        "quantity": 97,
        "imageLink": "\\images\\catalog\\foundation\\NYX-nude.png",
        "subCategoryID": "foundation",
        "rating": 4.3,
        "sellingCount": 3,
        "accessCount": 113
    },
    {
        "productID": "P028",
        "productName": "NYX-Can't Stop Won't Stop-Natural",
        "description": "",
        "price": 4200.00,
        "quantity": 89,
        "imageLink": "\\images\\catalog\\foundation\\NYX-natural.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "sellingCount": 103,
        "accessCount": 209
    },
    {
        "productID": "P029",
        "productName": "NYX-Can't Stop Won't Stop-True Beige",
        "description": "",
        "price": 4200.00,
        "quantity": 67,
        "imageLink": "\\images\\catalog\\foundation\\NYX-true-beige.png",
        "subCategoryID": "foundation",
        "rating": 4.5,
        "sellingCount": 93,
        "accessCount": 181
    },
    {
        "productID": "P030",
        "productName": "NYX-Can't Stop Won't Stop-Buff",
        "description": "",
        "price": 4200.00,
        "quantity": 92,
        "imageLink": "\\images\\catalog\\foundation\\NYX-buff.png",
        "subCategoryID": "foundation",
        "rating": 4.9,
        "sellingCount": 17,
        "accessCount": 118
    },
    {
        "productID": "P031",
        "productName": "NYX-Can't Stop Won't Stop-Medium Buff",
        "description": "",
        "price": 4200.00,
        "quantity": 71,
        "imageLink": "\\images\\catalog\\foundation\\NYX-medium-buff.png",
        "subCategoryID": "foundation",
        "rating": 4.9,
        "sellingCount": 109,
        "accessCount": 231
    },
    {
        "productID": "P032",
        "productName": "NYX-Can't Stop Won't Stop-Medium Olive",
        "description": "",
        "price": 4200.00,
        "quantity": 28,
        "imageLink": "\\images\\catalog\\foundation\\NYX-medium-olive.png",
        "subCategoryID": "foundation",
        "rating": 5.0,
        "sellingCount": 161,
        "accessCount": 267
    },
    {
        "productID": "P033",
        "productName": "NYX-Can't Stop Won't Stop-Soft Beige",
        "description": "",
        "price": 4200.00,
        "quantity": 83,
        "imageLink": "\\images\\catalog\\foundation\\NYX-soft-beige.png",
        "subCategoryID": "foundation",
        "rating": 4.8,
        "sellingCount": 102,
        "accessCount": 234
    },
    {
        "productID": "P034",
        "productName": "NARS-Afterglow Irresistible Eyeshadow Palette",
        "description": "",
        "price": 9590.00,
        "quantity": 83,
        "imageLink": "\\images\\catalog\\eyeshadow\\afterglow.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "sellingCount": 37,
        "accessCount": 192
    },
    {
        "productID": "P035",
        "productName": "Dasique-Berry Smoothie Eyeshadow Palette",
        "description": "",
        "price": 8000.00,
        "quantity": 57,
        "imageLink": "\\images\\catalog\\eyeshadow\\berry-smoothie.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.8,
        "sellingCount": 42,
        "accessCount": 178
    },
    {
        "productID": "P036",
        "productName": "Dasique-Candy Berry Eyeshadow Palette",
        "description": "",
        "price": 6950.00,
        "quantity": 68,
        "imageLink": "\\images\\catalog\\eyeshadow\\candy-berry.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "sellingCount": 39,
        "accessCount": 165
    },
    {
        "productID": "P037",
        "productName": "NYX-Ultimate Glow Shots Liquid Eyeshadow",
        "description": "",
        "price": 3000.00,
        "quantity": 95,
        "imageLink": "\\images\\catalog\\eyeshadow\\glowshots.png",
        "subCategoryID": "eyeshadow",
        "rating": 5.0,
        "sellingCount": 51,
        "accessCount": 220
    },
    {
        "productID": "P038",
        "productName": "NARS-Hardwired Eyeshadows",
        "description": "",
        "price": 4300.00,
        "quantity": 72,
        "imageLink": "\\images\\catalog\\eyeshadow\\hardwired.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "sellingCount": 34,
        "accessCount": 140
    },
    {
        "productID": "P039",
        "productName": "Huda Beauty-Icy Nude Eyeshadow Palette",
        "description": "",
        "price": 12500.00,
        "quantity": 43,
        "imageLink": "\\images\\catalog\\eyeshadow\\icy-nude.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.6,
        "sellingCount": 29,
        "accessCount": 110
    },
    {
        "productID": "P040",
        "productName": "NARS-Single Eyeshadows",
        "description": "",
        "price": 3700.00,
        "quantity": 81,
        "imageLink": "\\images\\catalog\\eyeshadow\\single.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "sellingCount": 47,
        "accessCount": 155
    },
    {
        "productID": "P041",
        "productName": "NYX-Ultimate Utopia 40 Pan Palette",
        "description": "",
        "price": 9800.00,
        "quantity": 64,
        "imageLink": "\\images\\catalog\\eyeshadow\\ultimate-utopia.png",
        "subCategoryID": "eyeshadow",
        "rating": 5.0,
        "sellingCount": 45,
        "accessCount": 170
    },
    {
        "productID": "P042",
        "productName": "NYX-Ultimate Vintage Jean Palette",
        "description": "",
        "price": 5600.00,
        "quantity": 78,
        "imageLink": "\\images\\catalog\\eyeshadow\\vintage-jean.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.9,
        "sellingCount": 38,
        "accessCount": 135
    },
    {
        "productID": "P043",
        "productName": "Dasique-Violet Knit Eyeshadow Palette",
        "description": "",
        "price": 6950.00,
        "quantity": 59,
        "imageLink": "\\images\\catalog\\eyeshadow\\violet-knit.png",
        "subCategoryID": "eyeshadow",
        "rating": 4.8,
        "sellingCount": 33,
        "accessCount": 125
    },
    {
        "productID": "P044",
        "productName": "NYX High Shine-Ambition Statement",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-ambition-statement.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P045",
        "productName": "NYX High Shine-Born to Hustle",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-born-to-hustle.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P046",
        "productName": "NYX High Shine-Movie",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-ambition-statement.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P047",
        "productName": "NYX High Shine-Boundary Pusher",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-boundary-pusher.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P048",
        "productName": "NYX High Shine-Goal Crusher",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-goal-crusher.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P049",
        "productName": "NYX High Shine-Goal Getter",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-goal-getter.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P050",
        "productName": "NYX High Shine-Movin' Up",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\nyx-movin-up.png",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P051",
        "productName": "NYX High Shine-Superstay Vinyl Ink-Charmed",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-charmed.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P052",
        "productName": "Maybelline Superstay Vinyl Ink-Cheeky",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-cheeky.jpg",
        "subCategoryID": "lipstick",
        "rating": 5.0,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P053",
        "productName": "Maybelline Superstay Vinyl Ink-Coy",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-coy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "sellingCount": 100,
        "accessCount": 250
    },
    {
        "productID": "P054",
        "productName": "Maybelline Superstay Vinyl Ink-Lippy",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-lippy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 130,
        "accessCount": 280
    },
    {
        "productID": "P055",
        "productName": "Maybelline Superstay Vinyl Ink-Peachy",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-peachy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 140,
        "accessCount": 290
    },
    {
        "productID": "P056",
        "productName": "Maybelline Superstay Vinyl Ink-Peppy",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-peppy.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "sellingCount": 110,
        "accessCount": 270
    },
    {
        "productID": "P057",
        "productName": "Maybelline Superstay Vinyl Ink-Pink Mashup",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-pink-mashup.jpg",
        "subCategoryID": "lipstick",
        "rating": 5.0,
        "sellingCount": 150,
        "accessCount": 310
    },
    {
        "productID": "P058",
        "productName": "Maybelline Superstay Vinyl Ink-Red Hot",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-red-hot.jpg",
        "subCategoryID": "lipstick",
        "rating": 5.0,
        "sellingCount": 160,
        "accessCount": 320
    },
    {
        "productID": "P059",
        "productName": "Maybelline Superstay Vinyl Ink-Rogue",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-rogue.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.9,
        "sellingCount": 135,
        "accessCount": 295
    },
    {
        "productID": "P060",
        "productName": "Maybelline Superstay Vinyl Ink-Unrivaled",
        "description": "",
        "price": 3650.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\lipstick\\mvi-unrivaled.jpg",
        "subCategoryID": "lipstick",
        "rating": 4.8,
        "sellingCount": 135,
        "accessCount": 295
    },
    {
        "productID": "P061",
        "productName": "Midnight Shades",
        "description": "Elegant black sunglasses with a sleek finish.",
        "price": 3000.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-1.png",
        "subCategoryID": "sunglasses",
        "rating": 4.9,
        "sellingCount": 120,
        "accessCount": 300
    },
    {
        "productID": "P062",
        "productName": "Notr Frames",
        "description": "Minimalist sunglasses with premium lens protection.",
        "price": 3500.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-2.png",
        "subCategoryID": "sunglasses",
        "rating": 4.9,
        "sellingCount": 110,
        "accessCount": 280
    },
    {
        "productID": "P063",
        "productName": "Eclipse Wear",
        "description": "Stylish dark-lensed sunglasses with UV protection.",
        "price": 3800.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-3.png",
        "subCategoryID": "sunglasses",
        "rating": 4.8,
        "sellingCount": 105,
        "accessCount": 260
    },
    {
        "productID": "P064",
        "productName": "Shadow Specs",
        "description": "Trendy oversized sunglasses for a bold look.",
        "price": 4500.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-4.png",
        "subCategoryID": "sunglasses",
        "rating": 4.7,
        "sellingCount": 100,
        "accessCount": 250
    },
    {
        "productID": "P065",
        "productName": "Amber Vision",
        "description": "Amber-tinted sunglasses for a sophisticated style.",
        "price": 3200.00,
        "quantity": 45,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-5.png",
        "subCategoryID": "sunglasses",
        "rating": 4.8,
        "sellingCount": 98,
        "accessCount": 240
    },
    {
        "productID": "P066",
        "productName": "Vintage Waves",
        "description": "Retro-style sunglasses with a classic design.",
        "price": 2800.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-6.png",
        "subCategoryID": "sunglasses",
        "rating": 4.7,
        "sellingCount": 90,
        "accessCount": 230
    },
    {
        "productID": "P067",
        "productName": "Sunset Glaze",
        "description": "Gradient-lens sunglasses for a chic summer look.",
        "price": 3900.00,
        "quantity": 35,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-7.png",
        "subCategoryID": "sunglasses",
        "rating": 4.9,
        "sellingCount": 110,
        "accessCount": 270
    },
    {
        "productID": "P068",
        "productName": "Crystal View",
        "description": "Transparent-frame sunglasses for a modern touch.",
        "price": 3100.00,
        "quantity": 42,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-8.png",
        "subCategoryID": "sunglasses",
        "rating": 4.6,
        "sellingCount": 95,
        "accessCount": 220
    },
    {
        "productID": "P069",
        "productName": "Ocean Blue",
        "description": "Blue-lens sunglasses with a sleek metallic frame.",
        "price": 3400.00,
        "quantity": 38,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-9.png",
        "subCategoryID": "sunglasses",
        "rating": 4.8,
        "sellingCount": 100,
        "accessCount": 250
    },
    {
        "productID": "P070",
        "productName": "Golden Luxe",
        "description": "Gold-plated frame sunglasses for a luxury appeal.",
        "price": 5000.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\sunglasses\\sg-10.png",
        "subCategoryID": "sunglasses",
        "rating": 5.0,
        "sellingCount": 130,
        "accessCount": 310
    },
    {
        "productID": "J001",
        "productName": "Pink Earrings",
        "description": "",
        "price": 3000.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\jewelry\\j1.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "sellingCount": 90,
        "accessCount": 200
    },
    {
        "productID": "J002",
        "productName": "Gold Flower Earrings",
        "description": "",
        "price": 2000.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\jewelry\\j2.png",
        "subCategoryID": "jewelry",
        "rating": 4.7,
        "sellingCount": 80,
        "accessCount": 180
    },
    {
        "productID": "J003",
        "productName": "Drop Earrings",
        "description": "",
        "price": 2500.00,
        "quantity": 35,
        "imageLink": "\\images\\catalog\\jewelry\\j3.png",
        "subCategoryID": "jewelry",
        "rating": 4.8,
        "sellingCount": 95,
        "accessCount": 210
    },
    {
        "productID": "J004",
        "productName": "Retro Pearl Earrings",
        "description": "",
        "price": 3500.00,
        "quantity": 25,
        "imageLink": "\\images\\catalog\\jewelry\\j4.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "sellingCount": 85,
        "accessCount": 190
    },
    {
        "productID": "J005",
        "productName": "Red Drop Earrings",
        "description": "",
        "price": 4500.00,
        "quantity": 20,
        "imageLink": "\\images\\catalog\\jewelry\\j5.png",
        "subCategoryID": "jewelry",
        "rating": 5.0,
        "sellingCount": 100,
        "accessCount": 220
    },
    {
        "productID": "J006",
        "productName": "Casual Studs",
        "description": "",
        "price": 2500.00,
        "quantity": 30,
        "imageLink": "\\images\\catalog\\jewelry\\j6.png",
        "subCategoryID": "jewelry",
        "rating": 4.8,
        "sellingCount": 90,
        "accessCount": 200
    },
    {
        "productID": "J007",
        "productName": "Blue Drop Earrings",
        "description": "",
        "price": 4500.00,
        "quantity": 20,
        "imageLink": "\\images\\catalog\\jewelry\\j7.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "sellingCount": 105,
        "accessCount": 230
    },
    {
        "productID": "J008",
        "productName": "Bow Pearl Earrings",
        "description": "",
        "price": 1500.00,
        "quantity": 40,
        "imageLink": "\\images\\catalog\\jewelry\\j8.png",
        "subCategoryID": "jewelry",
        "rating": 4.8,
        "sellingCount": 75,
        "accessCount": 170
    },
    {
        "productID": "J009",
        "productName": "Golden Hoops",
        "description": "",
        "price": 750.00,
        "quantity": 50,
        "imageLink": "\\images\\catalog\\jewelry\\j9.png",
        "subCategoryID": "jewelry",
        "rating": 4.6,
        "sellingCount": 110,
        "accessCount": 240
    },
    {
        "productID": "J010",
        "productName": "Sparkle Studs",
        "description": "",
        "price": 3500.00,
        "quantity": 25,
        "imageLink": "\\images\\catalog\\jewelry\\j10.png",
        "subCategoryID": "jewelry",
        "rating": 4.9,
        "sellingCount": 95,
        "accessCount": 215
    },
    {
        "productID": "J011",
        "productName": "Crystal Earrings",
        "description": "",
        "price": 4500.00,
        "quantity": 20,
        "imageLink": "\\images\\catalog\\jewelry\\j11.png",
        "subCategoryID": "jewelry",
        "rating": 5.0,
        "sellingCount": 120,
        "accessCount": 250
    }
]
category_collection = [
    {
        "categoryID": "C001",
        "categoryName": "Makeup"
    },
    {
        "categoryID": "C002",
        "categoryName": "Accessory"
    }
]
subcategory_collection = [
    {
        "subCategoryID": "blush",
        "subCategoryName": "blush",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "foundation",
        "subCategoryName": "foundation",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "eyeshadow",
        "subCategoryName": "eyeshadow",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "lipstick",
        "subCategoryName": "lipstick",
        "categoryID": "C001"
    },
    {
        "subCategoryID": "jewelry",
        "subCategoryName": "jewelry",
        "categoryID": "C002"
    },
    {
        "subCategoryID": "sunglasses",
        "subCategoryName": "sunglasses",
        "categoryID": "C002"
    }
]

if __name__ == "__main__":
    try:
        products_collection.insert_many(products)
        print("Products inserted successfully into the Products collection!")
    except Exception as e:
        print(f"Error inserting products: {e}")

